[/Script/EngineSettings.GeneralProjectSettings]
ProjectID=608EEAD04F814124A173BCAF1048BF57
ProjectName=First Person BP Game Template

[StartupActions]
bAddPacks=True
InsertPack=(PackSource="StarterContent.upack",PackName="StarterContent")

[/Script/UnrealEd.ProjectPackagingSettings]
; 将 Lua 脚本目录作为额外的非资产文件复制到打包目录
+DirectoriesToAlwaysStageAsNonUFS=(Path="Lua")